name: adyen_helper
description: Adyen custom card integration for Android and iOS. Provide bridge to encrypt credit card data for adyen payment endpoint.
version: 0.0.1
repository: https://github.com/AuroreT/adyen_helper

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dartdoc: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.auroret.adyen_helper
        pluginClass: AdyenHelperPlugin
      ios:
        pluginClass: AdyenHelperPlugin